### ISSUE TITLE
Issues page labels dont always show up.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/chrome_ext#15]
# issue

sometimes issue labels ( http://bits.owocki.com/032H3g0t0J1p/Screen%20Shot%202017-12-20%20at%206.28.50%20AM.png ) dont show up on issues pages

# repro steps

go to https://github.com/gitcoinco/chrome_ext/issues
if you navigate there, labels dont show up
if you hard refresh, labels _do_ show up.

**Comment by jclancy93** [comment]
Are you still having this problem?

**Comment by owocki** [comment]
uhm... not this exact issue.. but i am having an issue where _some_ bounties dont show up.

For example, at https://github.com/gitcoinco/web/issues
note that 'code ios landing page' doesnt have a gitcoin label by it http://bits.owocki.com/3V0A442R3e0V/Screen%20Shot%202017-12-26%20at%206.39.18%20PM.png
but if you navigate to https://github.com/gitcoinco/web/issues/174 youll see that it does in fact have a funding associated with it
