### ISSUE TITLE
This plugin makes chrome very stuttering

### ISSUE THREAD

**Issue by xwartz** [gitcoinco/chrome_ext#43]
The synchronous request is the murderer.

https://github.com/gitcoinco/chrome_ext/blob/master/src/script/pageload/functions.js#L25

https://github.com/gitcoinco/chrome_ext/blob/master/src/script/pageload/functions.js#L33

https://github.com/gitcoinco/chrome_ext/blob/master/src/script/pageload/functions.js#L41

**Comment by owocki** [comment]
thanks for noting this... im going to change this today

**Comment by owocki** [comment]
03307f8b8c46fdc4679dcb882d047e8e4b55c4a0

**Comment by owocki** [comment]
publishing to the chrome store now

**Comment by owocki** [comment]
published.. thanks @xwartz for the report
